// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvTU4ufGxTSI1NbMnn132tEZyWkZN-hJo',
    appId: '1:533077725967:web:ea8ff31d21867833fda47a',
    messagingSenderId: '533077725967',
    projectId: 'flutter-firebase-app-45269',
    authDomain: 'flutter-firebase-app-45269.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-45269.firebasestorage.app',
    measurementId: 'G-B5BKC972WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUBn6Edvpp2MDOmJx28Yz6V7Hf9_8nxJY',
    appId: '1:533077725967:android:d73e46d3be97b8a5fda47a',
    messagingSenderId: '533077725967',
    projectId: 'flutter-firebase-app-45269',
    storageBucket: 'flutter-firebase-app-45269.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnFrRJyhgPc86LEXBoflRh9BoofdHbdmU',
    appId: '1:533077725967:ios:b716ba5233a4a1e7fda47a',
    messagingSenderId: '533077725967',
    projectId: 'flutter-firebase-app-45269',
    storageBucket: 'flutter-firebase-app-45269.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnFrRJyhgPc86LEXBoflRh9BoofdHbdmU',
    appId: '1:533077725967:ios:b716ba5233a4a1e7fda47a',
    messagingSenderId: '533077725967',
    projectId: 'flutter-firebase-app-45269',
    storageBucket: 'flutter-firebase-app-45269.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvTU4ufGxTSI1NbMnn132tEZyWkZN-hJo',
    appId: '1:533077725967:web:2d1170dea9d08967fda47a',
    messagingSenderId: '533077725967',
    projectId: 'flutter-firebase-app-45269',
    authDomain: 'flutter-firebase-app-45269.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-45269.firebasestorage.app',
    measurementId: 'G-CV0SNW1PRW',
  );
}
